package com.github.aptemkov.unscramble.ui.game

const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

val allWordsList: List<Question> =
    listOf(
        Question("тэст", "Т э с т"),
        Question("гульня", "Г у л ь н я"),
        Question("расшыфруй", "р а с ш ы ф р у й"),
        Question("хата"),
        Question("бульба"),
        Question("цыбуля"),
        Question("бабуля"),
        Question("падручнік"),
        Question("сабака"),
        Question("дзеяч"),
        Question("тутэйшы"),
        Question("абабегчы"),
        Question("абабраць"),
        Question("абавязак"),
        Question("надвор'е"),
        Question("бізнэс"),
        Question("бусел"),
        Question("зубр"),
        Question("грошы"),
        Question("вадзяны"),
        Question("вайна"),
        Question("вогнішча"),
        Question("воўк"),
        Question("акуляры"),
        Question("выстаўка"),
        Question("гісторыя"),
        Question("галава"),
        Question("ганак"),
        Question("д'ябал"),
        Question("дагавор"),
        Question("ёгурт"),
        Question("жарт"),
        Question("жоўтавалосы"),
        Question("жэрабя"),
        Question("ілжывасць"),
        Question("ільняны"),
        Question("інтэлектуал"),
        Question("інтэлігенцыя"),
        Question("карумпаваны"),
        Question("лічэбнік"),
        Question("матуля"),
        Question("матывацыя"),
        Question("яблык"),
        Question("шчанюк"),
        Question("чабор"),
        Question("чалавекападобны"),
    )